name: 'Build and Release'

# ВРЕМЕННО: Запускать workflow только из ветки ci/debug-workflow
on:
  push:
    branches:
      - 'ci/debug-workflow'
  workflow_dispatch: # Оставляем для ручного запуска из интерфейса GitHub
  
#on:
#  push:
#    tags:
#      - 'v*'  # Workflow запускается при создании тега, например, v0.1.0

permissions:
  contents: write  # Нужно для создания релиза

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MinGW
        run: |
          choco install mingw -y
          echo "C:\tools\mingw64\bin" >> $GITHUB_PATH
      
      - name: Build
        run: make
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coflash-adapter
          path: coflash.exe

  release:
    needs: build  # Дожидается успешного завершения задачи 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: coflash-adapter

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: coflash_adapter.exe
          generate_release_notes: true